### ISSUE TITLE
One and done...

### ISSUE THREAD

**Issue by w1face** [humansandbag/Valheim-Better-Diving-Mod#1]
After I have surfaced and left the water, I can't dive anymore.  It simply says "You prepare to dive", but doesn't allow me to dive.

**Comment by humansandbag** [comment]
I'll look into this. Please let me know what other mods you are using.

**Comment by humansandbag** [comment]
I recently released a new version of the  mod. Are you able to reproduce the issue with the latest release?

**Comment by w1face** [comment]
Nope!  All perfect, thanks!
