### ISSUE TITLE
Controller does not work

### ISSUE THREAD

**Issue by ZenDragonX** [humansandbag/Valheim-Better-Diving-Mod#10]
**Describe the bug**
When using the controller the crouch button (Left Stick Click) does not do anything when in the water.  Can not enter Dive Mode.  Additionally, if I bypass that and reach over to the keyboard and hit ctrl to enter dive mode I still can not dive with the controller because no matter how much i point the camera down and try to swim I can not navigate under the water.  Once I reach for the mouse and keyboard everything works fine.

**To Reproduce**
1. Go to 'deep water'
2. click the left stick on xbox controller on pc.
3. try to swim underwater.  it doesn't work.  Try to point down and swim. no luck

**Expected behavior**
I expect an xbox controller connected to pc to work like PC mouse and keyboard.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version Widows 10

**Additional context**
None

**Comment by humansandbag** [comment]
Thank you for taking the time to report this potential bug. I am looking into this issue.

**Comment by humansandbag** [comment]
I have released v1.0.5 with a bug fix for this issue.
