### ISSUE TITLE
broken with 216.9

### ISSUE THREAD

**Issue by PaloAlo** [humansandbag/Valheim-Better-Diving-Mod#11]
needs updating for the new IG patch

**To Reproduce**
1. run the mod

**Steam and Windows 11

sry i didnt take a screenshot or post a logfile but if you run it you will see the issue right away. hoping you can update cause its a great mod

**Comment by jminnamon** [comment]
"failed to load: C:/.../Valheim/characters/character.fch.fch"
![image](https://github.com/humansandbag/Valheim-Better-Diving-Mod/assets/5620982/95d92b64-61d9-4173-9493-6be0bffde852)
for whatever reason it appears to have appended the file extension twice when trying to load the character.

![image](https://github.com/humansandbag/Valheim-Better-Diving-Mod/assets/5620982/55f3012c-c133-474d-a1c3-c67a3a2d8042)

Simply removing the mod resolves this.

(Edit: It revealed other problems with my mod setup that were unrelated to this.)

**Comment by humansandbag** [comment]
I have resolved the incompatibility with the Valheim patch 0.216.9 in version 1.0.7 of the mod and have uploaded a new release. It will be available on Thunderstore and Nexus shortly.

**Comment by PaloAlo** [comment]
thank you so much!

**Comment by PaloAlo** [comment]
hi, got a new error today. looks like this. steps to reproduce i cant really say as my server booted me for some Steam related reason and upon reconnecting i got this error.
![image](https://github.com/humansandbag/Valheim-Better-Diving-Mod/assets/107334373/59435ade-6a66-4ad3-a64f-9ca0efb8b787)

**Comment by humansandbag** [comment]
> hi, got a new error today. looks like this. steps to reproduce i cant really say as my server booted me for some Steam related reason and upon reconnecting i got this error. ![image](https://user-images.githubusercontent.com/107334373/249366135-59435ade-6a66-4ad3-a64f-9ca0efb8b787.png)

I can't recreate the errors in your screen shot. I am closing this issue since the original issue has been resolved. Please submit a new issue if this problem persists and make sure to provide detailed instructions for recreating it.
