### ISSUE TITLE
Hildir update

### ISSUE THREAD

**Issue by PaloAlo** [humansandbag/Valheim-Better-Diving-Mod#13]
[Error  : Unity Log] MissingMethodException: void Character.UseStamina(single)
Stack trace:
(wrapper dynamic-method) Character.DMD<Character::UpdateSwimming>(Character,single)
(wrapper dynamic-method) Character.DMD<Character::UpdateMotion>(Character,single)
(wrapper dynamic-method) Character.DMD<Character::CustomFixedUpdate>(Character)
(wrapper dynamic-method) MonoUpdaters.DMD<MonoUpdaters::FixedUpdate>(MonoUpdaters)

it has an additional param that you are missing

**Comment by humansandbag** [comment]
Thank you. I am aware of the issue and am working to resolve it.

**Comment by humansandbag** [comment]
I have updated the mod to be compatible with the latest version of the game.
