### ISSUE TITLE
Camera stuck when logging onto dedicated server

### ISSUE THREAD

**Issue by Mofker** [humansandbag/Valheim-Better-Diving-Mod#16]
When logging onto a dedicated server. The camera will get stuck on the ground and spam the following message into the console:

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterDiving.Patches.GameCamera_UpdateCamera.Prefix (GameCamera __instance, UnityEngine.Camera ___m_camera) (at <aebcfc3b1c3744ad806da8b7c72fbe20>:0)
(wrapper dynamic-method) GameCamera.DMD<GameCamera::UpdateCamera>(GameCamera,single)
GameCamera.LateUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
```

What it looks like ingame:
![Untitled](https://github.com/humansandbag/Valheim-Better-Diving-Mod/assets/38079264/163e1654-eb86-4b85-9c72-c5ba48b24e4b)

**Comment by humansandbag** [comment]
I am unable to recreate this issue. It is possible that you are using an incompatible mod.
