### ISSUE TITLE
Ashlands update

### ISSUE THREAD

**Issue by PaloAlo** [humansandbag/Valheim-Better-Diving-Mod#17]
[Info   :   BepInEx] Loading [BetterDiving 1.0.9]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type WaterVolume and name Update2 and parameters 
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void BetterDiving.Patches.WaterVolume_Update::Prefix(WaterVolume __instance, Single[]& ___m_normalizedDepth)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
BetterDiving.BetterDiving.Awake () (at <aebcfc3b1c3744ad806da8b7c72fbe20>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

updated to Ashlands today and getting this error. 
game version Valheim 0.218.15

**Comment by humansandbag** [comment]
I'm working on this issue.

**Comment by humansandbag** [comment]
This is fixed as of version 1.1.0.
