### ISSUE TITLE
filename includes /

### ISSUE THREAD

**Issue by BETLOG** [humansandbag/Valheim-Better-Diving-Mod#20]
**Describe the bug**
filename includes /

**To Reproduce**
extract or preview the zip for 1.1.1 or 1.1.0

**Expected behavior**
not this
if you intend to put the dll in a `/MainStreetGaming-BetterDiving` subdirectory... then you are doing it wrong :)

**Screenshots**
Dolphin (file manager)
![2024-10-30--13-14-42_betlogbeast_mediausersteamdataTOOLSvalheimmodsMainStreetGamingBetterDiving111Dolphin](https://github.com/user-attachments/assets/7afc7cd3-9ec8-4dbf-b136-552b80c7c85e)
Ark (archive/zip manager)
![2024-10-30--13-19-53_betlogbeast_MainStreetGamingBetterDiving111zipArk](https://github.com/user-attachments/assets/661038da-c2b6-40b4-ab05-022886feeb1f)

**Desktop (please complete the following information):**
Kubuntu 24.04

**Additional context**

**Comment by humansandbag** [comment]
This appears to be an issue with the Ark archive manager and does not occur with other archive managers I've tested.
