### ISSUE TITLE
Multiplayer - No diving Skill, No Breath meter drain underwater

### ISSUE THREAD

**Issue by RokennGit** [humansandbag/Valheim-Better-Diving-Mod#7]
Just installed this on a multiplayer server and while most of the features work there are a couple that do not seem to be functioning.

1. When diving the breath meter shows up as empty and has no drain effect.
2. There is No new diving skill in the skills list, and no leveling up of a diving skill has been noticed.

Notes:
-using this with Jotunn V 2.11 (tested with Jontunn 2.10.4 and had same issues).
-Images/files attached show issues as well as values on debug page.
-all other features work without issue.
-there appears to be a beath drain happening because at a certain point, the player does seem to lose breath and take large hits to stamina, it just doesn't show on the meter at all.
-I have tried putting the plugin on the server side as well and have the same issues.
-Noticed this in the boot up logs for BepInEx: "
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace: Valheim_Diving_Mod.MainClass.MainClass.Start () (at <3f789a3b2b0d4188b6aedee12cb2d8bb>:0)"]

Files:

![SkillsNoDiving](https://user-images.githubusercontent.com/47937714/227375781-b92b03a5-805a-42bd-8e0d-3bfe866e46e9.PNG)
[BetterDivingLog.txt](https://github.com/humansandbag/Valheim-Better-Diving-Mod/files/11056722/BetterDivingLog.txt)

**Comment by humansandbag** [comment]
It sounds like the mod cannot find the assets because they're in the wrong directory. I'd suggest using r2modman to download it/manage your mods if you are not. The next version of the mod is going to have all assets embedded in the binary so that it can be placed anywhere in the bepinex plugins directory.
