### ISSUE TITLE
Incompatible with Project Auga

### ISSUE THREAD

**Issue by PoPoWanObi** [humansandbag/Valheim-Better-Diving-Mod#8]
**Describe the bug**
When the two mods are installed [Project Auga and Better Diving] the player is unable to move.

**To Reproduce**
1. Install both mods and try to play

**Expected behavior**
Harmony

![image](https://user-images.githubusercontent.com/20360617/229647309-d656a323-ddc4-470c-baf5-0551a1fbdb13.png)

**Comment by humansandbag** [comment]
Thank you for taking the time to report a potential bug. I am unable to reproduce this issue and have thoroughly tested Project Auga with this mod.
