### ISSUE TITLE
Mod is being filtered out of Linux Dedicated Server due to executable filter

### ISSUE THREAD

**Issue by gdragon-git** [humansandbag/Valheim-Better-Diving-Mod#9]
Hi my dedicated server log is showing: 

[Warning:   BepInEx] Skipping [Valheim Better Diving 1.0.4] because of process filters (valheim.exe)

Looks like your filtering it out on linux dedicated servers, did you know? 

OS: Linux 0e6e581be63f 5.19.17-Unraid  (Slackware)
Docker: lloesche/valheim-server-docker
Mod version 1.0.4
Bepinex Version 5.4.2102
Valheim Version 0.214.305

**Comment by humansandbag** [comment]
Is this causing an issue? The clients should sync the config from the server, but the mod itself is really only client-side code and shouldn't execute on the server.

**Comment by gdragon-git** [comment]
But doesn't the config sync code run from within the mod? If so, then it would need to run on the server and, right now, the message indicates that the mod is not being run by the server due to the process filter. I've seen other mod makers have issues with setting this up right.

**Comment by humansandbag** [comment]
Thank you. I am removing the process filter in the next release. As of v1.0.6, it will no longer have the process filter.

**Comment by humansandbag** [comment]
v1.0.6 has been released. The mod no longer has the process filter.
